In [59]:
import pandas as pd
from functools import reduce
import os

In [62]:
resource_path = './data'
only_files = [os.path.join(resource_path, f) for f in os.listdir(resource_path) if os.path.isfile(os.path.join(resource_path, f)) 
              and f.find('.csv') != -1]
dfs = []
for f in only_files:
    df = pd.read_csv(f)
    dfs.append(df)
citibike_combo = pd.concat(dfs)
citibike_combo.head()
citibike_combo.to_csv('citibike_combo_data.csv', sep = ',')
citibike_combo.head()

,tripduration,starttime,stoptime,start station id,start station name,start station latitude,start station longitude,end station id,end station name,end station latitude,end station longitude,bikeid,usertype,birth year,gender
0,316,2019-06-01 00:05:55.7210,2019-06-01 00:11:11.9940,3187,Warren St,40.721124,-74.038051,3199,Newport Pkwy,40.728745,-74.032108,29677,Subscriber,1993,1
1,280,2019-06-01 00:08:09.0920,2019-06-01 00:12:50.0730,3185,City Hall,40.717733,-74.043845,3267,Morris Canal,40.712419,-74.038526,29571,Subscriber,1984,1
2,2162,2019-06-01 00:13:11.8800,2019-06-01 00:49:14.3640,3199,Newport Pkwy,40.728745,-74.032108,3199,Newport Pkwy,40.728745,-74.032108,26208,Customer,1969,0
3,2184,2019-06-01 00:13:30.1110,2019-06-01 00:49:54.2250,3199,Newport Pkwy,40.728745,-74.032108,3199,Newport Pkwy,40.728745,-74.032108,29487,Customer,1969,0
4,139,2019-06-01 00:13:31.8520,2019-06-01 00:15:51.7880,3207,Oakland Ave,40.737604,-74.052478,3207,Oakland Ave,40.737604,-74.052478,29592,Subscriber,1994,1

In [43]:
filepath1 = "data/JC-201906-citibike-tripdata.csv"
jun19_df = pd.read_csv(filepath1)
jun19_df.head()

,tripduration,starttime,stoptime,start station id,start station name,start station latitude,start station longitude,end station id,end station name,end station latitude,end station longitude,bikeid,usertype,birth year,gender
0,316,2019-06-01 00:05:55.7210,2019-06-01 00:11:11.9940,3187,Warren St,40.721124,-74.038051,3199,Newport Pkwy,40.728745,-74.032108,29677,Subscriber,1993,1
1,280,2019-06-01 00:08:09.0920,2019-06-01 00:12:50.0730,3185,City Hall,40.717733,-74.043845,3267,Morris Canal,40.712419,-74.038526,29571,Subscriber,1984,1
2,2162,2019-06-01 00:13:11.8800,2019-06-01 00:49:14.3640,3199,Newport Pkwy,40.728745,-74.032108,3199,Newport Pkwy,40.728745,-74.032108,26208,Customer,1969,0
3,2184,2019-06-01 00:13:30.1110,2019-06-01 00:49:54.2250,3199,Newport Pkwy,40.728745,-74.032108,3199,Newport Pkwy,40.728745,-74.032108,29487,Customer,1969,0
4,139,2019-06-01 00:13:31.8520,2019-06-01 00:15:51.7880,3207,Oakland Ave,40.737604,-74.052478,3207,Oakland Ave,40.737604,-74.052478,29592,Subscriber,1994,1

In [44]:
filepath2 = "data/JC-201907-citibike-tripdata.csv"
jul19_df = pd.read_csv(filepath2)
jul19_df.head()

,tripduration,starttime,stoptime,start station id,start station name,start station latitude,start station longitude,end station id,end station name,end station latitude,end station longitude,bikeid,usertype,birth year,gender
0,1793,2019-07-01 00:00:36.6150,2019-07-01 00:30:30.5940,3186,Grove St PATH,40.719586,-74.043117,3198,Heights Elevator,40.748716,-74.040443,29595,Subscriber,1978,1
1,434,2019-07-01 00:02:54.6150,2019-07-01 00:10:09.0370,3206,Hilltop,40.731169,-74.057574,3280,Astor Place,40.719282,-74.071262,29647,Subscriber,1988,1
2,251,2019-07-01 00:03:27.5670,2019-07-01 00:07:38.6080,3186,Grove St PATH,40.719586,-74.043117,3205,JC Medical Center,40.716540,-74.049638,26271,Subscriber,1986,1
3,636,2019-07-01 00:03:56.1690,2019-07-01 00:14:32.4180,3206,Hilltop,40.731169,-74.057574,3281,Leonard Gordon Park,40.745910,-74.057271,26225,Customer,1996,2
4,623,2019-07-01 00:04:16.2060,2019-07-01 00:14:40.0500,3206,Hilltop,40.731169,-74.057574,3281,Leonard Gordon Park,40.745910,-74.057271,29230,Customer,1989,1

In [45]:
filepath3 = "data/JC-201908-citibike-tripdata.csv"
aug19_df = pd.read_csv(filepath3)
aug19_df.head()

,tripduration,starttime,stoptime,start station id,start station name,start station latitude,start station longitude,end station id,end station name,end station latitude,end station longitude,bikeid,usertype,birth year,gender
0,261,2019-08-01 00:14:55.9900,2019-08-01 00:19:17.4780,3205,JC Medical Center,40.716540,-74.049638,3192,Liberty Light Rail,40.711242,-74.055701,26268,Subscriber,1980,1
1,172,2019-08-01 00:23:06.9910,2019-08-01 00:25:59.1480,3279,Dixon Mills,40.721630,-74.049968,3186,Grove St PATH,40.719586,-74.043117,26162,Subscriber,1996,1
2,525,2019-08-01 00:23:28.6170,2019-08-01 00:32:13.7000,3199,Newport Pkwy,40.728745,-74.032108,3203,Hamilton Park,40.727596,-74.044247,29279,Subscriber,1991,1
3,219,2019-08-01 00:32:36.1410,2019-08-01 00:36:15.2730,3187,Warren St,40.721124,-74.038051,3185,City Hall,40.717733,-74.043845,29598,Subscriber,1988,1
4,262,2019-08-01 00:41:26.6700,2019-08-01 00:45:49.3530,3186,Grove St PATH,40.719586,-74.043117,3272,Jersey & 3rd,40.723332,-74.045953,26162,Subscriber,1960,1

In [46]:
filepath4 = "data/JC-202006-citibike-tripdata.csv"
jun20_df = pd.read_csv(filepath4)
jun20_df.head()

,tripduration,starttime,stoptime,start station id,start station name,start station latitude,start station longitude,end station id,end station name,end station latitude,end station longitude,bikeid,usertype,birth year,gender
0,122,2020-06-01 00:02:21.7500,2020-06-01 00:04:24.3250,3792,Columbus Dr at Exchange Pl,40.716870,-74.032810,3639,Harborside,40.719252,-74.034234,42489,Subscriber,1987,1
1,1282,2020-06-01 00:12:27.1090,2020-06-01 00:33:50.0540,3198,Heights Elevator,40.748716,-74.040443,3276,Marin Light Rail,40.714584,-74.042817,42183,Subscriber,1988,1
2,186,2020-06-01 01:19:59.2090,2020-06-01 01:23:05.8930,3275,Columbus Drive,40.718355,-74.038914,3681,Grand St,40.715178,-74.037683,42140,Subscriber,1987,1
3,131,2020-06-01 01:26:42.2050,2020-06-01 01:28:53.8040,3267,Morris Canal,40.712419,-74.038526,3681,Grand St,40.715178,-74.037683,42120,Subscriber,1987,1
4,266,2020-06-01 01:27:33.7090,2020-06-01 01:32:00.1890,3639,Harborside,40.719252,-74.034234,3186,Grove St PATH,40.719586,-74.043117,42437,Subscriber,1972,2

In [47]:
filepath5 = "data/JC-202007-citibike-tripdata.csv"
jul20_df = pd.read_csv(filepath5)
jul20_df.head()

,tripduration,starttime,stoptime,start station id,start station name,start station latitude,start station longitude,end station id,end station name,end station latitude,end station longitude,bikeid,usertype,birth year,gender
0,2333,2020-07-01 00:23:19.8220,2020-07-01 01:02:13.2980,3694,Jackson Square,40.711130,-74.078900,3276,Marin Light Rail,40.714584,-74.042817,42579,Customer,1969,0
1,1203,2020-07-01 00:27:45.2420,2020-07-01 00:47:49.1960,3791,Hoboken Ave at Monmouth St,40.735208,-74.046964,3202,Newport PATH,40.727224,-74.033759,42564,Subscriber,1965,1
2,786,2020-07-01 00:34:17.8680,2020-07-01 00:47:24.6310,3792,Columbus Dr at Exchange Pl,40.716870,-74.032810,3225,Baldwin at Montgomery,40.723659,-74.064194,42219,Subscriber,1994,1
3,1488,2020-07-01 00:51:07.5310,2020-07-01 01:15:56.0200,3677,Glenwood Ave,40.727551,-74.071061,3194,McGinley Square,40.725340,-74.067622,44424,Subscriber,1995,2
4,2682,2020-07-01 00:51:16.3880,2020-07-01 01:35:58.4590,3191,Union St,40.718211,-74.083639,3193,Lincoln Park,40.724605,-74.078406,42186,Subscriber,1993,1

In [48]:
filepath6 = "data/JC-202008-citibike-tripdata.csv"
aug20_df = pd.read_csv(filepath6)
aug20_df.head()

,tripduration,starttime,stoptime,start station id,start station name,start station latitude,start station longitude,end station id,end station name,end station latitude,end station longitude,bikeid,usertype,birth year,gender
0,561,2020-08-01 00:00:16.5960,2020-08-01 00:09:38.5610,3185,City Hall,40.717733,-74.043845,3185,City Hall,40.717733,-74.043845,42303,Customer,1994,2
1,236,2020-08-01 00:00:46.3900,2020-08-01 00:04:42.8890,3186,Grove St PATH,40.719586,-74.043117,3270,Jersey & 6th St,40.725289,-74.045572,44989,Subscriber,1996,1
2,384,2020-08-01 00:02:38.9250,2020-08-01 00:09:03.7590,3186,Grove St PATH,40.719586,-74.043117,3203,Hamilton Park,40.727596,-74.044247,41696,Subscriber,1984,2
3,1302,2020-08-01 00:03:27.0270,2020-08-01 00:25:09.2120,3185,City Hall,40.717733,-74.043845,3185,City Hall,40.717733,-74.043845,42310,Customer,1993,1
4,5561,2020-08-01 00:03:57.4810,2020-08-01 01:36:38.5000,3185,City Hall,40.717733,-74.043845,3185,City Hall,40.717733,-74.043845,42346,Customer,1995,2

In [49]:
jun19_df = jun19_df.loc[jun19_df["gender"] != 0, :]
jun19_df

,tripduration,starttime,stoptime,start station id,start station name,start station latitude,start station longitude,end station id,end station name,end station latitude,end station longitude,bikeid,usertype,birth year,gender
0,316,2019-06-01 00:05:55.7210,2019-06-01 00:11:11.9940,3187,Warren St,40.721124,-74.038051,3199,Newport Pkwy,40.728745,-74.032108,29677,Subscriber,1993,1
1,280,2019-06-01 00:08:09.0920,2019-06-01 00:12:50.0730,3185,City Hall,40.717733,-74.043845,3267,Morris Canal,40.712419,-74.038526,29571,Subscriber,1984,1
4,139,2019-06-01 00:13:31.8520,2019-06-01 00:15:51.7880,3207,Oakland Ave,40.737604,-74.052478,3207,Oakland Ave,40.737604,-74.052478,29592,Subscriber,1994,1
5,203,2019-06-01 00:15:43.2590,2019-06-01 00:19:06.7450,3203,Hamilton Park,40.727596,-74.044247,3269,Brunswick & 6th,40.726012,-74.050389,26316,Subscriber,1978,1
6,671,2019-06-01 00:19:41.5790,2019-06-01 00:30:52.6600,3202,Newport PATH,40.727224,-74.033759,3278,Monmouth and 6th,40.725685,-74.048790,29488,Subscriber,1970,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
39425,639,2019-06-30 23:38:29.5450,2019-06-30 23:49:09.2110,3677,Glenwood Ave,40.727551,-74.071061,3191,Union St,40.718211,-74.083639,29197,Customer,1986,1
39426,643,2019-06-30 23:38:34.9100,2019-06-30 23:49:17.9690,3677,Glenwood Ave,40.727551,-74.071061,3191,Union St,40.718211,-74.083639,26262,Customer,1990,2
39427,418,2019-06-30 23:42:30.9400,2019-06-30 23:49:29.5360,3679,Bergen Ave,40.722104,-74.071455,3191,Union St,40.718211,-74.083639,29241,Subscriber,1979,1
39428,2529,2019-06-30 23:46:17.5700,2019-07-01 00:28:27.1710,3185,City Hall,40.717733,-74.043845,3213,Van Vorst Park,40.718489,-74.047727,26254,Subscriber,1982,1
39429,831,2019-06-30 23:49:01.6830,2019-07-01 00:02:53.1150,3210,Pershing Field,40.742677,-74.051789,3186,Grove St PATH,40.719586,-74.043117,29551,Subscriber,1988,1

In [50]:
jul19_df = jul19_df.loc[jul19_df["gender"] != 0, :]
jul19_df

,tripduration,starttime,stoptime,start station id,start station name,start station latitude,start station longitude,end station id,end station name,end station latitude,end station longitude,bikeid,usertype,birth year,gender
0,1793,2019-07-01 00:00:36.6150,2019-07-01 00:30:30.5940,3186,Grove St PATH,40.719586,-74.043117,3198,Heights Elevator,40.748716,-74.040443,29595,Subscriber,1978,1
1,434,2019-07-01 00:02:54.6150,2019-07-01 00:10:09.0370,3206,Hilltop,40.731169,-74.057574,3280,Astor Place,40.719282,-74.071262,29647,Subscriber,1988,1
2,251,2019-07-01 00:03:27.5670,2019-07-01 00:07:38.6080,3186,Grove St PATH,40.719586,-74.043117,3205,JC Medical Center,40.716540,-74.049638,26271,Subscriber,1986,1
3,636,2019-07-01 00:03:56.1690,2019-07-01 00:14:32.4180,3206,Hilltop,40.731169,-74.057574,3281,Leonard Gordon Park,40.745910,-74.057271,26225,Customer,1996,2
4,623,2019-07-01 00:04:16.2060,2019-07-01 00:14:40.0500,3206,Hilltop,40.731169,-74.057574,3281,Leonard Gordon Park,40.745910,-74.057271,29230,Customer,1989,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
43741,673,2019-07-31 23:39:13.1800,2019-07-31 23:50:26.6520,3681,Grand St,40.715178,-74.037683,3277,Communipaw & Berry Lane,40.714358,-74.066611,26284,Subscriber,1987,1
43742,161,2019-07-31 23:41:24.1110,2019-07-31 23:44:05.4090,3211,Newark Ave,40.721525,-74.046305,3203,Hamilton Park,40.727596,-74.044247,29570,Subscriber,1998,1
43743,310,2019-07-31 23:47:27.3940,2019-07-31 23:52:37.4870,3195,Sip Ave,40.730897,-74.063913,3678,Fairmount Ave,40.725726,-74.071959,26237,Subscriber,1977,1
43744,137,2019-07-31 23:59:29.9300,2019-08-01 00:01:47.1970,3199,Newport Pkwy,40.728745,-74.032108,3638,Washington St,40.724294,-74.035483,29121,Subscriber,1993,1
43745,463,2019-07-31 23:59:54.9470,2019-08-01 00:07:37.9750,3199,Newport Pkwy,40.728745,-74.032108,3203,Hamilton Park,40.727596,-74.044247,29259,Subscriber,1988,1

In [51]:
aug19_df = aug19_df.loc[aug19_df["gender"] != 0, :]
aug19_df

,tripduration,starttime,stoptime,start station id,start station name,start station latitude,start station longitude,end station id,end station name,end station latitude,end station longitude,bikeid,usertype,birth year,gender
0,261,2019-08-01 00:14:55.9900,2019-08-01 00:19:17.4780,3205,JC Medical Center,40.716540,-74.049638,3192,Liberty Light Rail,40.711242,-74.055701,26268,Subscriber,1980,1
1,172,2019-08-01 00:23:06.9910,2019-08-01 00:25:59.1480,3279,Dixon Mills,40.721630,-74.049968,3186,Grove St PATH,40.719586,-74.043117,26162,Subscriber,1996,1
2,525,2019-08-01 00:23:28.6170,2019-08-01 00:32:13.7000,3199,Newport Pkwy,40.728745,-74.032108,3203,Hamilton Park,40.727596,-74.044247,29279,Subscriber,1991,1
3,219,2019-08-01 00:32:36.1410,2019-08-01 00:36:15.2730,3187,Warren St,40.721124,-74.038051,3185,City Hall,40.717733,-74.043845,29598,Subscriber,1988,1
4,262,2019-08-01 00:41:26.6700,2019-08-01 00:45:49.3530,3186,Grove St PATH,40.719586,-74.043117,3272,Jersey & 3rd,40.723332,-74.045953,26162,Subscriber,1960,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
48706,384,2019-08-31 23:40:45.2450,2019-08-31 23:47:09.8810,3639,Harborside,40.719252,-74.034234,3203,Hamilton Park,40.727596,-74.044247,29522,Subscriber,1988,1
48707,633,2019-08-31 23:45:55.6660,2019-08-31 23:56:29.5350,3186,Grove St PATH,40.719586,-74.043117,3185,City Hall,40.717733,-74.043845,29679,Customer,1997,1
48708,324,2019-08-31 23:50:27.9220,2019-08-31 23:55:52.8420,3276,Marin Light Rail,40.714584,-74.042817,3211,Newark Ave,40.721525,-74.046305,26198,Subscriber,1997,2
48709,126,2019-08-31 23:52:21.9250,2019-08-31 23:54:28.5820,3211,Newark Ave,40.721525,-74.046305,3209,Brunswick St,40.724176,-74.050656,29512,Subscriber,1998,1
48710,690,2019-08-31 23:56:55.1530,2019-09-01 00:08:25.2370,3185,City Hall,40.717733,-74.043845,3277,Communipaw & Berry Lane,40.714358,-74.066611,26223,Subscriber,1992,1

In [55]:
combine19_df = pd.concat([jun19_df, jul19_df, aug19_df], axis=0)
combine19_df

,tripduration,starttime,stoptime,start station id,start station name,start station latitude,start station longitude,end station id,end station name,end station latitude,end station longitude,bikeid,usertype,birth year,gender
0,316,2019-06-01 00:05:55.7210,2019-06-01 00:11:11.9940,3187,Warren St,40.721124,-74.038051,3199,Newport Pkwy,40.728745,-74.032108,29677,Subscriber,1993,1
1,280,2019-06-01 00:08:09.0920,2019-06-01 00:12:50.0730,3185,City Hall,40.717733,-74.043845,3267,Morris Canal,40.712419,-74.038526,29571,Subscriber,1984,1
4,139,2019-06-01 00:13:31.8520,2019-06-01 00:15:51.7880,3207,Oakland Ave,40.737604,-74.052478,3207,Oakland Ave,40.737604,-74.052478,29592,Subscriber,1994,1
5,203,2019-06-01 00:15:43.2590,2019-06-01 00:19:06.7450,3203,Hamilton Park,40.727596,-74.044247,3269,Brunswick & 6th,40.726012,-74.050389,26316,Subscriber,1978,1
6,671,2019-06-01 00:19:41.5790,2019-06-01 00:30:52.6600,3202,Newport PATH,40.727224,-74.033759,3278,Monmouth and 6th,40.725685,-74.048790,29488,Subscriber,1970,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
48706,384,2019-08-31 23:40:45.2450,2019-08-31 23:47:09.8810,3639,Harborside,40.719252,-74.034234,3203,Hamilton Park,40.727596,-74.044247,29522,Subscriber,1988,1
48707,633,2019-08-31 23:45:55.6660,2019-08-31 23:56:29.5350,3186,Grove St PATH,40.719586,-74.043117,3185,City Hall,40.717733,-74.043845,29679,Customer,1997,1
48708,324,2019-08-31 23:50:27.9220,2019-08-31 23:55:52.8420,3276,Marin Light Rail,40.714584,-74.042817,3211,Newark Ave,40.721525,-74.046305,26198,Subscriber,1997,2
48709,126,2019-08-31 23:52:21.9250,2019-08-31 23:54:28.5820,3211,Newark Ave,40.721525,-74.046305,3209,Brunswick St,40.724176,-74.050656,29512,Subscriber,1998,1
48710,690,2019-08-31 23:56:55.1530,2019-09-01 00:08:25.2370,3185,City Hall,40.717733,-74.043845,3277,Communipaw & Berry Lane,40.714358,-74.066611,26223,Subscriber,1992,1

In [57]:
grp_combine19 = combine19_df.groupby(['gender'])

grp_combine19_df = grp_combine19.mean()
grp_combine19_df

,tripduration,start station id,start station latitude,start station longitude,end station id,end station latitude,end station longitude,bikeid,birth year
gender,,,,,,,,,
1,636.276099,3298.738764,40.722701,-74.046140,3296.236371,40.722328,-74.045744,28452.047843,1982.179101
2,811.270602,3289.589451,40.722695,-74.046293,3285.613194,40.722391,-74.045629,28419.757738,1984.068254

In [58]:
grp_user19 = combine19_df.groupby(['usertype'])
grp_user19_df = grp_user19.count()
grp_user19_df

,tripduration,starttime,stoptime,start station id,start station name,start station latitude,start station longitude,end station id,end station name,end station latitude,end station longitude,bikeid,birth year,gender
usertype,,,,,,,,,,,,,,
Customer,10694,10694,10694,10694,10694,10694,10694,10694,10694,10694,10694,10694,10694,10694
Subscriber,110238,110238,110238,110238,110238,110238,110238,110238,110238,110238,110238,110238,110238,110238

In [28]:
jun19_df = jun19_df.loc[jun19_df["tripduration"] < 3600, :]
jun19_df

,tripduration,starttime,stoptime,start station id,start station name,start station latitude,start station longitude,end station id,end station name,end station latitude,end station longitude,bikeid,usertype,birth year,gender
0,316,2019-06-01 00:05:55.7210,2019-06-01 00:11:11.9940,3187,Warren St,40.721124,-74.038051,3199,Newport Pkwy,40.728745,-74.032108,29677,Subscriber,1993,1
1,280,2019-06-01 00:08:09.0920,2019-06-01 00:12:50.0730,3185,City Hall,40.717733,-74.043845,3267,Morris Canal,40.712419,-74.038526,29571,Subscriber,1984,1
4,139,2019-06-01 00:13:31.8520,2019-06-01 00:15:51.7880,3207,Oakland Ave,40.737604,-74.052478,3207,Oakland Ave,40.737604,-74.052478,29592,Subscriber,1994,1
5,203,2019-06-01 00:15:43.2590,2019-06-01 00:19:06.7450,3203,Hamilton Park,40.727596,-74.044247,3269,Brunswick & 6th,40.726012,-74.050389,26316,Subscriber,1978,1
6,671,2019-06-01 00:19:41.5790,2019-06-01 00:30:52.6600,3202,Newport PATH,40.727224,-74.033759,3278,Monmouth and 6th,40.725685,-74.048790,29488,Subscriber,1970,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
39425,639,2019-06-30 23:38:29.5450,2019-06-30 23:49:09.2110,3677,Glenwood Ave,40.727551,-74.071061,3191,Union St,40.718211,-74.083639,29197,Customer,1986,1
39426,643,2019-06-30 23:38:34.9100,2019-06-30 23:49:17.9690,3677,Glenwood Ave,40.727551,-74.071061,3191,Union St,40.718211,-74.083639,26262,Customer,1990,2
39427,418,2019-06-30 23:42:30.9400,2019-06-30 23:49:29.5360,3679,Bergen Ave,40.722104,-74.071455,3191,Union St,40.718211,-74.083639,29241,Subscriber,1979,1
39428,2529,2019-06-30 23:46:17.5700,2019-07-01 00:28:27.1710,3185,City Hall,40.717733,-74.043845,3213,Van Vorst Park,40.718489,-74.047727,26254,Subscriber,1982,1
39429,831,2019-06-30 23:49:01.6830,2019-07-01 00:02:53.1150,3210,Pershing Field,40.742677,-74.051789,3186,Grove St PATH,40.719586,-74.043117,29551,Subscriber,1988,1

In [25]:
jul19_df = jul19_df.loc[jul19_df["tripduration"] < 3600, :]
jul19_df

,tripduration,starttime,stoptime,start station id,start station name,start station latitude,start station longitude,end station id,end station name,end station latitude,end station longitude,bikeid,usertype,birth year,gender
0,1793,2019-07-01 00:00:36.6150,2019-07-01 00:30:30.5940,3186,Grove St PATH,40.719586,-74.043117,3198,Heights Elevator,40.748716,-74.040443,29595,Subscriber,1978,1
1,434,2019-07-01 00:02:54.6150,2019-07-01 00:10:09.0370,3206,Hilltop,40.731169,-74.057574,3280,Astor Place,40.719282,-74.071262,29647,Subscriber,1988,1
2,251,2019-07-01 00:03:27.5670,2019-07-01 00:07:38.6080,3186,Grove St PATH,40.719586,-74.043117,3205,JC Medical Center,40.716540,-74.049638,26271,Subscriber,1986,1
3,636,2019-07-01 00:03:56.1690,2019-07-01 00:14:32.4180,3206,Hilltop,40.731169,-74.057574,3281,Leonard Gordon Park,40.745910,-74.057271,26225,Customer,1996,2
4,623,2019-07-01 00:04:16.2060,2019-07-01 00:14:40.0500,3206,Hilltop,40.731169,-74.057574,3281,Leonard Gordon Park,40.745910,-74.057271,29230,Customer,1989,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
43741,673,2019-07-31 23:39:13.1800,2019-07-31 23:50:26.6520,3681,Grand St,40.715178,-74.037683,3277,Communipaw & Berry Lane,40.714358,-74.066611,26284,Subscriber,1987,1
43742,161,2019-07-31 23:41:24.1110,2019-07-31 23:44:05.4090,3211,Newark Ave,40.721525,-74.046305,3203,Hamilton Park,40.727596,-74.044247,29570,Subscriber,1998,1
43743,310,2019-07-31 23:47:27.3940,2019-07-31 23:52:37.4870,3195,Sip Ave,40.730897,-74.063913,3678,Fairmount Ave,40.725726,-74.071959,26237,Subscriber,1977,1
43744,137,2019-07-31 23:59:29.9300,2019-08-01 00:01:47.1970,3199,Newport Pkwy,40.728745,-74.032108,3638,Washington St,40.724294,-74.035483,29121,Subscriber,1993,1
43745,463,2019-07-31 23:59:54.9470,2019-08-01 00:07:37.9750,3199,Newport Pkwy,40.728745,-74.032108,3203,Hamilton Park,40.727596,-74.044247,29259,Subscriber,1988,1

In [41]:
grp_jun19_df

In [ ]:
dfs = [jun19_df, jul19_df, aug19_df]
df19_final = reduce(lambda left,right: pd.merge(left,right,on='bikeid'), dfs)
df19_final.head()

In [5]:
combined_df.to_csv("Data/combined_state.csv", encoding="utf-8", index=False, header=True)
final_df = combined_df.rename(columns={' cocktail':'cocktail', 'Image URL':'image_src'})
final_df

,abbr,latitude,longitude,state,cocktail,image_src
0,AL,32.601011,-86.680736,Alabama,Hurricane,https://www.recipegirl.com/wp-content/uploads/...
1,AK,61.302501,-158.775020,Alaska,Boston Sour,https://www.thewinebuzz.com/wp-content/webp-ex...
2,AZ,34.168219,-111.930907,Arizona,Count Camillo's Paloma,https://i0.wp.com/www.imbored-letsgo.com/wp-co...
3,AR,34.751928,-92.131378,Arkansas,Daiquiri,https://www.liquor.com/thmb/8yIf61iidysFKWT7-b...
4,CA,37.271875,-119.270415,California,Count Camillo's Paloma,https://i0.wp.com/www.imbored-letsgo.com/wp-co...
5,CO,38.997934,-105.550567,Colorado,Hurricane,https://www.recipegirl.com/wp-content/uploads/...
6,CT,41.518784,-72.757507,Connecticut,Margarita,https://www.thecocktaildb.com/images/media/dri...
7,DE,39.145251,-75.418921,Delaware,Screwdriver,https://www.thecocktaildb.com/images/media/dri...
8,DC,38.899349,-77.014567,District of Columbia,Fancy Whiskey,https://cdn.hiconsumption.com/wp-content/uploa...
9,FL,27.975728,-83.833017,Florida,Daiquiri,https://www.liquor.com/thmb/8yIf61iidysFKWT7-b...
10,GA,32.678125,-83.222976,Georgia,Georgia Peach,https://4.bp.blogspot.com/-NYzi_YGNPCM/Uhz2XgW...
11,HI,20.460000,-157.505000,Hawaii,Lemon Drop,https://1.bp.blogspot.com/-meD5dsc-ieM/XClM-wh...
12,ID,45.494576,-114.142430,Idaho,Cosmopolitan,https://www.thecocktaildb.com/images/media/dri...
13,IL,39.739318,-89.504139,Illinois,Manhattan Cocktail (dry),https://www.thecocktaildb.com/images/media/dri...
14,IN,39.766219,-86.441277,Indiana,Lemon Drop,https://1.bp.blogspot.com/-meD5dsc-ieM/XClM-wh...
15,IA,41.938317,-93.389798,Iowa,Cosmopolitan,https://www.thecocktaildb.com/images/media/dri...
16,KS,38.498779,-98.320078,Kansas,Screwdriver,https://www.thecocktaildb.com/images/media/dri...
17,KY,37.822294,-85.768240,Kentucky,Mint Julep (Southern Style),https://hips.hearstapps.com/hmg-prod.s3.amazon...
18,LA,30.973377,-91.429910,Louisiana,Hurricane,https://www.recipegirl.com/wp-content/uploads/...
19,ME,45.218513,-69.014866,Maine,Margarita,https://www.thecocktaildb.com/images/media/dri...
20,MD,38.806352,-77.268416,Maryland,Bloody Mary,https://assets.bonappetit.com/photos/57aceb5af...
21,MA,42.062940,-71.718067,Massachusetts,Fancy Whiskey,https://cdn.hiconsumption.com/wp-content/uploa...
22,MI,44.943560,-86.415805,Michigan,Cosmopolitan,https://www.thecocktaildb.com/images/media/dri...
23,MN,46.441859,-93.365515,Minnesota,Bloody Mary,https://assets.bonappetit.com/photos/57aceb5af...
24,MS,32.585106,-89.877220,Mississippi,Long Island Iced Tea,https://www.supergoldenbakes.com/wordpress/wp-...
25,MO,38.304662,-92.437099,Missouri,Moscow Mule,https://media2.s-nbcnews.com/j/newscms/2016_19...
26,MT,46.679800,-110.044783,Montana,Moscow Mule,https://media2.s-nbcnews.com/j/newscms/2016_19...
27,NE,41.500819,-99.680902,Nebraska,Fancy Whiskey,https://cdn.hiconsumption.com/wp-content/uploa...
28,NV,38.502032,-117.023060,Nevada,Grasshopper Cocktail,https://magicskillet.com/wp-content/uploads/20...
29,NH,44.001231,-71.579923,New Hampshire,Fancy Whiskey,https://cdn.hiconsumption.com/wp-content/uploa...
30,NJ,40.143006,-74.731116,New Jersey,Manhattan Cocktail (dry),https://www.thecocktaildb.com/images/media/dri...
31,NM,34.166232,-106.026069,New Mexico,Fancy Whiskey,https://cdn.hiconsumption.com/wp-content/uploa...
32,NY,40.705626,-73.979680,New York,Manhattan Cocktail (dry),https://www.thecocktaildb.com/images/media/dri...
33,NC,35.214563,-79.891267,North Carolina,Cherry Rum,https://data.thefeedfeed.com/static/2020/02/17...
34,ND,47.467882,-100.302266,North Dakota,Cosmopolitan,https://www.thecocktaildb.com/images/media/dri...
35,OH,40.190362,-82.669252,Ohio,Fancy Whiskey,https://cdn.hiconsumption.com/wp-content/uploa...
36,OK,35.309765,-98.716558,Oklahoma,White Russian,https://d2lswn7b0fl4u2.cloudfront.net/photos/p...
37,OR,44.141905,-120.538099,Oregon,Fancy Whiskey,https://cdn.hiconsumption.com/wp-content/uploa...
38,PA,40.994593,-77.604698,Pennsylvania,Boston Sour,https://www.thewinebuzz.com/wp-content/webp-ex...
39,RI,41.582728,-71.506451,Rhode Island,Cosmopolitan,https://www.thecocktaildb.com/images/media/dri...
40,SC,33.625050,-80.947038,South Carolina,Tequila Sunrise,https://www.thecocktaildb.com/images/media/dri...
41,SD,44.212699,-100.247164,South Dakota,Screwdriver,https://www.thecocktaildb.com/images/media/dri...
42,TN,35.830521,-85.978599,Tennessee,Horse's Neck (With A Kick),https://www.sidewalkshoes.com/wp-content/uploa...
43,TX,31.169336,-100.076842,Texas,Count Camillo's Paloma,https://i0.wp.com/www.imbored-letsgo.com/wp-co...
44,UT,39.499761,-111.547028,Utah,Cape Codder,https://tmbidigitalassetsazure.blob.core.windo...
45,VT,43.871755,-72.447783,Vermont,Cosmopolitan,https://www.thecocktaildb.com/images/media/dri...
46,VA,38.003386,-79.458786,Virginia,Fancy Whiskey,https://cdn.hiconsumption.com/wp-content/uploa...
47,WA,38.899349,-77.014567,Washington,Fancy Whiskey,https://cdn.hiconsumption.com/wp-content/uploa...
48,WV,38.920171,-80.181691,West Virginia,Cosmopolitan,https://www.thecocktaildb.com/images/media/dri...
49,WI,44.786297,-89.826705,Wisconsin,Grasshopper Cocktail,https://magicskillet.com/wp-content/uploads/20...
50,WY,43.000325,-107.554567,Wyoming,White Russian,https://d2lswn7b0fl4u2.cloudfront.net/photos/p...

## Postgres for state table

In [6]:
from sqlalchemy import create_engine
from config import postgres_pwd, postgres_user

db_name = "cocktail_db"
table_name = "state"

connection_string = f"{postgres_user}:{postgres_pwd}@localhost:5432/{db_name}"
engine = create_engine(f'postgresql://{connection_string}')
conn = engine.connect()

final_df.to_sql(table_name, con=engine, if_exists="append", index=False)

conn.close()